import type { ArtistProfile } from './types';

const ARTIST_IMG_BASE = "https://storage.googleapis.com/salondesinconnus/Artistes/";

export const ARTISTS_ROSTER: ArtistProfile[] = [
  {
    id: 1,
    name: "Alex T. St-Laurent",
    class: "Cinéma, Photo, Théâtre, Direction",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}452646238_470313905737215_5551835217518244963_n (1).jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Cinéma",
    subjects: ["Art"],
    stats: { creativity: 99, technique: 90, vision: 100 },
    bio: "Cinéma, Photo, Théâtre, Direction. Tous les Liens",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 2,
    name: "Emilie Guertin Lavictoire",
    class: "Huile sur Toile, Sculpture de Masques",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}e0b555c8-dd87-4711-b4eb-779f889a389f (1).jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Peinture",
    subjects: ["Masques"],
    stats: { creativity: 90, technique: 95, vision: 90 },
    bio: "[Expo en Cours] Collection",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 3,
    name: "Yuri Rousseau",
    class: "Sculpture et Estampe sur Papier Artisanal",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}441804cf-a6ff-4278-9552-ca0a7516a828.jpeg`,
    galleryImages: [],
    location: "Namur",
    medium: "Papier Artisanal",
    subjects: [],
    stats: { creativity: 92, technique: 90, vision: 92 },
    bio: "[Expo en Cours] Boutique",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 4,
    name: "Krystelle Levert",
    class: "Peinture - Dessin",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}69df94b2-09db-4447-b517-15e9271b6a4e.jpeg`,
    galleryImages: [],
    location: "Namur",
    medium: "Peinture",
    subjects: [],
    stats: { creativity: 88, technique: 90, vision: 88 },
    bio: "Boutique",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 5,
    name: "Tania Martin",
    class: "Musique",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}oqqArs4S41o-HD.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Musique",
    subjects: [],
    stats: { creativity: 95, technique: 90, vision: 95 },
    bio: "Tous les Liens",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 6,
    name: "Sebastien Leblanc",
    class: "Violon",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}thumbnail sebastien leblanc one for all 1.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Violon",
    subjects: [],
    stats: { creativity: 90, technique: 98, vision: 90 },
    bio: "Soundcloud",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 7,
    name: "Louis-Julien Durso",
    class: "Auteur Compositeur Metteur en Scene",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}lj1 copy.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Scene",
    subjects: [],
    stats: { creativity: 96, technique: 90, vision: 96 },
    bio: "Musique : Auteur Compositeur Metteur en Scene, Interprete. Tous les Liens",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 8,
    name: "La Bronze",
    class: "Musique",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}vignes et cam.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Chant",
    subjects: [],
    stats: { creativity: 95, technique: 92, vision: 95 },
    bio: "Youtube",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 9,
    name: "Leslie",
    class: "Musique",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}EXP15_1.48.1.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Chant",
    subjects: [],
    stats: { creativity: 90, technique: 90, vision: 90 },
    bio: "Mysterion",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 10,
    name: "Captain Generous",
    class: "Musique",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}generous thumbnail 2 screenshot.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Guitare",
    subjects: [],
    stats: { creativity: 92, technique: 90, vision: 90 },
    bio: "Spotify",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 11,
    name: "Magnetosphere",
    class: "Musique Experimentale",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}buJf1H0Im6w-HD.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Experimentale",
    subjects: [],
    stats: { creativity: 98, technique: 90, vision: 98 },
    bio: "Video",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 12,
    name: "Charles - Antoine Goulet",
    class: "Poesie",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}TgTHhvQ9UJI-HD.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Mots",
    subjects: [],
    stats: { creativity: 95, technique: 85, vision: 90 },
    bio: "Video",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 13,
    name: "Max & Nora",
    class: "Graffiti",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}max nora screenshot.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Spray Paint",
    subjects: [],
    stats: { creativity: 95, technique: 92, vision: 95 },
    bio: "Instagram",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 14,
    name: "Cynthia Filion",
    class: "Murales - Artiste Peintre",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}cynthia.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Murales",
    subjects: [],
    stats: { creativity: 94, technique: 90, vision: 94 },
    bio: "Fueled by love ❤️. Chef de cuisine. Instagram",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 15,
    name: "Kyle Murray - Kmurrs",
    class: "Musique",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}kyle.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Guitare",
    subjects: [],
    stats: { creativity: 90, technique: 92, vision: 90 },
    bio: "Website",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 16,
    name: "Charlotte l'Orage",
    class: "Écriture - Evenements Lunaires",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}318738950_2919417445020452_468726909170826473_n.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Plume",
    subjects: [],
    stats: { creativity: 96, technique: 88, vision: 96 },
    bio: "Creations Lunaires",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 17,
    name: "Claude Philippe Nolin",
    class: "Arts Visuels",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}CPNolin-n-b.png`,
    galleryImages: [],
    location: "Namur",
    medium: "Mixte",
    subjects: [],
    stats: { creativity: 92, technique: 90, vision: 92 },
    bio: "Boutique",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 18,
    name: "Mariel Sharp",
    class: "Cinema",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}WHERE-THE-WITCH-LIVES_Mariel-Sharp_Director-Headshot-1-400x600.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Film",
    subjects: [],
    stats: { creativity: 95, technique: 95, vision: 95 },
    bio: "Film: Where The Witch Lives",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 19,
    name: "Kamy Rheault",
    class: "Art Actuel, Peinture, Sculpture",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}artists on the road banner vanilla .png`,
    galleryImages: [],
    location: "Namur",
    medium: "Installation",
    subjects: [],
    stats: { creativity: 98, technique: 90, vision: 98 },
    bio: "Peinture, Sculpture, Installations. Instagram",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 20,
    name: "Alice Renard",
    class: "Écriture",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}b5878991-9619-4ba7-b34c-1a7995f9a179.jpeg`,
    galleryImages: [],
    location: "Namur",
    medium: "Plume",
    subjects: [],
    stats: { creativity: 94, technique: 92, vision: 94 },
    bio: "Wikipedia",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 21,
    name: "Jean-Guilhem Barguès",
    class: "Arts Numeriques",
    category: "DIGITAL",
    avatarUrl: `${ARTIST_IMG_BASE}jean-guilhem-bargues-futuristic-slums-small.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Digital",
    subjects: [],
    stats: { creativity: 95, technique: 98, vision: 95 },
    bio: "Artstation",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 22,
    name: "Zora Katsner",
    class: "Tatouage, Huile, Violon, Decors",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}395495582_295421856713027_7848845889443417373_n.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Mixte",
    subjects: [],
    stats: { creativity: 95, technique: 90, vision: 95 },
    bio: "Decors. All Links",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 23,
    name: "Marc-Alexis Pepin",
    class: "Cuisine Artistique",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}13736082_681443872003519_178441360_n (1)-gigapixel-standard-scale-6_00x_edited_edited.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Gastronomie",
    subjects: [],
    stats: { creativity: 98, technique: 98, vision: 98 },
    bio: "Labo culinaire",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 24,
    name: "Antony Lepage",
    class: "Musique - Mixage Sonore",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}459542201_10229549860623644_6079757919980949171_n.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Son",
    subjects: [],
    stats: { creativity: 90, technique: 98, vision: 90 },
    bio: "Studio D'enregistrement",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 25,
    name: "Les Bobettes",
    class: "Musique: Chants Polyphoniques",
    category: "MUSIC",
    avatarUrl: `${ARTIST_IMG_BASE}bobettes_1.1.1 copy mirror.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Voix",
    subjects: [],
    stats: { creativity: 92, technique: 92, vision: 92 },
    bio: "Ripon Trad",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 26,
    name: "Alice Traverse",
    class: "Art visuel-Médiums mixtes",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}175689470_167233801936163_440157860285754846_n.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Mixte",
    subjects: [],
    stats: { creativity: 95, technique: 90, vision: 95 },
    bio: "Onirique, absurde, macabre et normal. Combo figuratif. Site",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 27,
    name: "Alex Alisich",
    class: "Photographie",
    category: "VISUAL",
    avatarUrl: `${ARTIST_IMG_BASE}12710986_1103477433006489_292645079324933309_o.jpg`,
    galleryImages: [],
    location: "Namur",
    medium: "Photo",
    subjects: [],
    stats: { creativity: 90, technique: 95, vision: 90 },
    bio: "Behance",
    links: { buy: "#", website: "#", support: "#" }
  }
];
