// Les textes de la Communauté, à part pour garder textes.ts sous 500 lignes.
// textes.ts les range sous la clé `social`.

export const SOCIAL_FR = {
  votreCompte: 'Votre compte',
  compteAide: 'Le même compte qu’au Salon des Inconnus. Il garde votre nom, vos amis et votre bilan d’un appareil à l’autre.',
  atouts: [
    'Un profil avec votre bannière et la statuette que vous avez gagnée',
    'Des amis, leurs tables ouvertes et leurs défis',
    'Des messages à deux ou en groupe',
    'Une partie contre un inconnu en un geste',
  ],
  porteAide: 'Connectez-vous pour trouver des amis.',
  seConnecter: 'Se connecter',
  creerCompte: 'Créer un compte',
  oubli: 'Mot de passe oublié',
  courriel: 'Courriel',
  motDePasse: 'Mot de passe',
  nomJoueur: 'Nom de joueur',
  envoyerLien: 'Recevoir le lien',
  lienEnvoye: 'Un lien vous attend dans votre boîte de courriel.',
  avecGoogle: 'Continuer avec Google',
  pasDeCompte: 'Pas encore de compte ?',
  dejaCompte: 'J’ai déjà un compte',
  seDeconnecter: 'Se déconnecter',
  modifierProfil: 'Modifier le profil',
  enregistrer: 'Enregistrer',
  bio: 'Un mot sur vous',
  bioVide: 'Aucun mot pour l’instant.',
  banniere: 'Bannière',
  statCampagne: (b: number, t: number) => `Campagne : ${b} sur ${t} adversaires battus`,
  bilan: (v: number, d: number) => `En ligne : ${v} victoire${v > 1 ? 's' : ''}, ${d} défaite${d > 1 ? 's' : ''}`,
  enLigne: 'En ligne',
  horsLigne: 'Absent',
  ecrire: 'Écrire',
  defier: 'Défier',
  retirer: 'Retirer de mes amis',
  bloquer: 'Faire taire',
  debloquer: 'Rendre la parole',
  bloques: (n: number) => `${n} joueur${n > 1 ? 's' : ''} réduit${n > 1 ? 's' : ''} au silence`,
  signaler: 'Signaler',
  signalerTitre: (nom: string) => `Signaler ${nom}`,
  signalerAide: 'Dites à l’équipe du Salon ce qui s’est passé. Votre signalement reste entre vous et elle.',
  signale: 'Merci. L’équipe du Salon lira votre signalement.',
  demandesRecues: 'Demandes reçues',
  accepter: 'Accepter',
  refuser: 'Refuser',
  enAttente: 'Demande envoyée',
  amisVide: 'Cherchez un joueur par son nom pour l’ajouter à vos amis.',
  chercherJoueur: 'Chercher un joueur',
  chercher: 'Chercher',
  ajouter: 'Ajouter',
  aucunResultat: 'Personne ne porte ce nom.',
  tableSuite: 'tient une table ouverte',
  tablePubliee: 'Vos amis voient votre table ouverte.',
  messages: 'Messages',
  messagesVide: 'Écrivez à un ami depuis la liste, ou ouvrez un salon de groupe.',
  creerGroupe: 'Ouvrir un salon de groupe',
  nomGroupe: 'Nom du salon',
  inviterAmis: 'Inviter des amis',
  inviter: 'Inviter un ami',
  creer: 'Ouvrir',
  quitter: 'Quitter le salon',
  membres: (n: number) => `${n} membre${n > 1 ? 's' : ''}`,
  filVide: 'Le premier mot vous revient.',
  ecrireMessage: 'Votre message',
  envoyer: 'Envoyer',
  envoiRefuse: 'Ce message n’a pas pu partir.',
  defierInconnu: 'Affronter un inconnu',
  inconnuConnexion: 'Connectez-vous pour affronter un inconnu ou défier vos amis.',
  defiEnvoye: 'reçoit votre défi',
  defiAttente: 'Votre table est ouverte. Il reste',
  defiRecu: 'vous défie',
  defiRecuAide: 'Sa table est ouverte. Acceptez et la partie commence.',
  defiRefuse: (nom: string) => `${nom} décline le défi pour cette fois.`,
  defiExpire: 'Le défi a expiré sans réponse.',
  defiImpossible: 'Le défi n’a pas pu partir.',
  recherche: 'À la recherche d’un adversaire',
  rechercheAide: 'Votre table est ouverte au premier venu. Il reste',
  rechercheTrouve: 'Un adversaire arrive à votre table.',
  rechercheVide: 'Personne ne s’est présenté. Réessayez dans un moment.',
  lienLent: 'Le lien ne s’ouvre pas. Certains réseaux bloquent le jeu de pair à pair; un autre réseau, ou un nouvel essai, règle souvent la chose.',
  reessayer: 'Réessayer',
  rejoindreCode: 'Rejoindre avec un code',
  amisEnLigne: (n: number) => `${n} ami${n > 1 ? 's' : ''} en ligne`,
  nonLus: (n: number) => `${n} message${n > 1 ? 's' : ''} non lu${n > 1 ? 's' : ''}`,
};

export const SOCIAL_EN: typeof SOCIAL_FR = {
  votreCompte: 'Your account',
  compteAide: 'The same account as at Le Salon des Inconnus. It keeps your name, your friends and your record across devices.',
  atouts: [
    'A profile with your banner and the figurine you earned',
    'Friends, their open tables and their challenges',
    'Messages one to one or in groups',
    'A game against a stranger in one tap',
  ],
  porteAide: 'Sign in to find friends.',
  seConnecter: 'Sign in',
  creerCompte: 'Create an account',
  oubli: 'Forgot password',
  courriel: 'Email',
  motDePasse: 'Password',
  nomJoueur: 'Player name',
  envoyerLien: 'Send me the link',
  lienEnvoye: 'A link is waiting in your inbox.',
  avecGoogle: 'Continue with Google',
  pasDeCompte: 'No account yet?',
  dejaCompte: 'I already have an account',
  seDeconnecter: 'Sign out',
  modifierProfil: 'Edit profile',
  enregistrer: 'Save',
  bio: 'A word about you',
  bioVide: 'Nothing here yet.',
  banniere: 'Banner',
  statCampagne: (b, t) => `Campaign: ${b} of ${t} opponents beaten`,
  bilan: (v, d) => `Online: ${v} win${v === 1 ? '' : 's'}, ${d} loss${d === 1 ? '' : 'es'}`,
  enLigne: 'Online',
  horsLigne: 'Away',
  ecrire: 'Message',
  defier: 'Challenge',
  retirer: 'Remove friend',
  bloquer: 'Block',
  debloquer: 'Unblock',
  bloques: (n) => `${n} blocked player${n === 1 ? '' : 's'}`,
  signaler: 'Report',
  signalerTitre: (nom) => `Report ${nom}`,
  signalerAide: 'Tell the Salon team what happened. Your report stays between you and them.',
  signale: 'Thank you. The Salon team will read your report.',
  demandesRecues: 'Friend requests',
  accepter: 'Accept',
  refuser: 'Decline',
  enAttente: 'Request sent',
  amisVide: 'Search for a player by name to add them as a friend.',
  chercherJoueur: 'Find a player',
  chercher: 'Search',
  ajouter: 'Add',
  aucunResultat: 'Nobody goes by that name.',
  tableSuite: 'has an open table',
  tablePubliee: 'Your friends can see your open table.',
  messages: 'Messages',
  messagesVide: 'Message a friend from the list, or open a group room.',
  creerGroupe: 'Open a group room',
  nomGroupe: 'Room name',
  inviterAmis: 'Invite friends',
  inviter: 'Invite a friend',
  creer: 'Open',
  quitter: 'Leave the room',
  membres: (n) => `${n} member${n === 1 ? '' : 's'}`,
  filVide: 'The first word is yours.',
  ecrireMessage: 'Your message',
  envoyer: 'Send',
  envoiRefuse: 'This message could not be sent.',
  defierInconnu: 'Play a stranger',
  inconnuConnexion: 'Sign in to play a stranger or challenge your friends.',
  defiEnvoye: 'has your challenge',
  defiAttente: 'Your table is open. Time left',
  defiRecu: 'challenges you',
  defiRecuAide: 'Their table is open. Accept and the game begins.',
  defiRefuse: (nom) => `${nom} declines the challenge this time.`,
  defiExpire: 'The challenge expired without an answer.',
  defiImpossible: 'The challenge could not be sent.',
  recherche: 'Looking for an opponent',
  rechercheAide: 'Your table is open to the first comer. Time left',
  rechercheTrouve: 'An opponent is coming to your table.',
  rechercheVide: 'Nobody showed up. Try again in a moment.',
  lienLent: 'The link will not open. Some networks block peer to peer play; another network or a fresh try often settles it.',
  reessayer: 'Try again',
  rejoindreCode: 'Join with a code',
  amisEnLigne: (n) => `${n} friend${n === 1 ? '' : 's'} online`,
  nonLus: (n) => `${n} unread message${n === 1 ? '' : 's'}`,
};
