import { chromium } from 'playwright';
const URL = 'http://localhost:5178/?intro=0';
const nav = await chromium.launch();
const ouvrir = async (nom) => {
  const ctx = await nav.newContext({ viewport: { width: 1440, height: 900 } });
  const p = await ctx.newPage();
  p.on('pageerror', (e) => console.log(nom, 'pageerror', e.message));
  await p.goto(URL, { waitUntil: 'domcontentloaded' });
  await p.waitForSelector('.menu', { state: 'attached', timeout: 60000 });
  await p.fill('input.saisie >> nth=0', nom);
  return p;
};
const A = await ouvrir('Alex');
const B = await ouvrir('Kamy');
const idA = (await A.textContent('code.id')).trim();
const idB = (await B.textContent('code.id')).trim();
console.log('ids', idA, idB);
await A.click('text=Ouvrir une table', { force: true });
await A.waitForSelector('.etat-lien', { state: 'attached', timeout: 20000 });
console.log('A attente');
await B.fill('input[placeholder="paisho-xxxxxxxx"]', idA);
await B.click('text=Rejoindre', { force: true });
const t0 = Date.now();
await Promise.all([A.waitForSelector('.hud', { state: 'attached', timeout: 40000 }), B.waitForSelector('.hud', { state: 'attached', timeout: 40000 })]);
console.log('connectés en', Date.now() - t0, 'ms');
const nomsA = await A.$$eval('.joueur-nom', (l) => l.map((x) => x.textContent));
const nomsB = await B.$$eval('.joueur-nom', (l) => l.map((x) => x.textContent));
console.log('noms', nomsA, nomsB);
// L'hôte joue l'ouverture, l'invité doit la recevoir.
await A.waitForFunction(() => window.__partie?.legaux?.length > 0);
await A.evaluate(() => { const c = window.__partie.legaux[0]; window.__scene.surClic(null); return c; });
const coup = await A.evaluate(() => window.__partie.legaux[0]);
await A.click('.hud-gauche .jeton.jouable >> nth=0', { force: true });
await A.waitForFunction(() => window.__partie.choix === 'reserve');
const porte = await A.evaluate(() => window.__partie.legaux.find((c) => c.type === 'planter').porte);
await A.evaluate((p) => window.__scene.surClic(p), porte);
await B.waitForFunction(() => window.__partie?.coups?.length === 1, null, { timeout: 15000 });
console.log('coup reçu par B', await B.evaluate(() => window.__partie.coups));
const amis = async (p) => p.evaluate(() => JSON.parse(localStorage.getItem('paisho.amis') || '[]'));
console.log('amis A', await amis(A));
console.log('amis B', await amis(B));
await B.click('text=Menu', { force: true });
await B.waitForSelector('.amis', { state: 'attached', timeout: 10000 });
await B.screenshot({ path: 'captures/v-amis-1440.jpg', quality: 70, type: 'jpeg' });
console.log('liste amis B', await B.$$eval('.amis li', (l) => l.map((x) => x.textContent)));
await nav.close();
