import type { ArtistProfile } from './types';

const ROSTER_BASE_URL = "https://storage.googleapis.com/salondesinconnus/Artistes/";

export const ARTISTS_ROSTER: ArtistProfile[] = [
  {
    id: 1,
    name: "Alex T. St-Laurent",
    class: "The Director",
    category: "DIGITAL",
    avatarUrl: `${ROSTER_BASE_URL}Alex.jpg`,
    galleryImages: [
        "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1000&auto=format&fit=crop"
    ],
    location: "Namur",
    medium: "Cinéma, Photo, Théâtre, Direction",
    subjects: ["Philosophie", "Spiritualité", "Fantastique", "sexualité", "Alchimie"],
    skills: ["Creative Direction", "Photography", "Filmmaking", "Event Planning"],
    currentExpos: "Au Salon des Inconnus",
    stats: { creativity: 99, technique: 85, vision: 100 },
    bio: "Fondateur et directeur du Salon des inconnus, Alex rajoute à sa mission artistique celle de tenir l'espace et de supporter un lieu rassembleur, guérisseur et créatif. Fervent défenseur de l'Art libre, il aspire à connaître les inconnus de ce monde et de bâtir les ponts nécessaires à la réalisation dans la matière, à la cocréation consciente et profonde qui contribue à l'évolution de tous.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 2,
    name: "Emilie G. Lavictoire",
    class: "Nature Sentinel",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}Emilie.jpg`,
    galleryImages: [
        "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1633511090164-b43840ea1607?q=80&w=1000&auto=format&fit=crop"
    ],
    location: "Ripon",
    medium: "Huile sur Toile, Sculpture de Masques",
    subjects: ["Féminisme", "clitoris", "nature", "autonomie", "diversité"],
    skills: ["Oil Painting", "Mask Making", "Illustration", "Agriculture"],
    currentExpos: "Milieux humides, Nostalgica Pub, Ottawa, On",
    stats: { creativity: 88, technique: 85, vision: 90 },
    bio: "Citoyenne rurale engagée et ardente défenseuse de l'égalité entre les humains. Emilie est dessinatrice féministe. Née au Québec et gâtée plus que nécessaire par notre société de consommation. À l'âge adulte, elle s'est mise au service de la communauté comme productrice agricole et créatrice d'illustrations percutantes.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 3,
    name: "Yuri Rousseau",
    class: "Paper Mage",
    category: "SCULPTURE",
    avatarUrl: `${ROSTER_BASE_URL}Yuri.jpg`,
    galleryImages: [
        "https://images.unsplash.com/photo-1549887534-1541e9326642?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1501472312651-726efe1188c1?q=80&w=1000&auto=format&fit=crop"
    ],
    location: "Ripon",
    medium: "Sculpture et Estampe sur Papier Artisanal",
    subjects: ["Droits humains", "nature", "parentalité", "connexions", "écologie"],
    skills: ["Papermaking", "Sculpture", "Printmaking", "Jewelry"],
    currentExpos: "Milieux humides, Nostalgica Pub, Ottawa, On",
    stats: { creativity: 92, technique: 96, vision: 88 },
    bio: "Y'a pas grand chose que Yuri Rousseau ne fait pas. Sculpture, gravures, estampes, bijouterie, et maintenant \"Papa\". Yuri démontre ça veut dire quoi \"masculin sacré\", il est un exemple magnifique d'une belle balance des 4 archétypes.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 4,
    name: "Krystel Levert",
    class: "Ink Alchemist",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}Krystel.jpg`, 
    galleryImages: [
        "https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1578301978693-85e6c0c67947?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1580130379745-139a67ac7403?q=80&w=1000&auto=format&fit=crop"
    ],
    location: "Ripon",
    medium: "Peinture - Dessin",
    subjects: ["Féminisme", "nature", "autonomie", "diversité"],
    skills: ["Drawing", "Painting", "Social Art", "Workshops"],
    currentExpos: "Milieux humides, Nostalgica Pub, Ottawa, On",
    stats: { creativity: 95, technique: 90, vision: 98 },
    bio: "Citoyenne rurale engagée et ardente défenseuse de l'égalité entre les humains. Krystel est dessinatrice féministe. Cette artiste contemporaine utilise entre autre son art pour tisser des liens avec des organismes communautaires qui oeuvrent auprès de clientèles vulnérables.",
    links: {
        buy: "#",
        website: "#",
        support: "#"
    }
  },
  {
    id: 5,
    name: "Marc Alexis Pepin",
    class: "Culinary Alchemist",
    category: "SCULPTURE",
    avatarUrl: `${ROSTER_BASE_URL}MarcAlexis.jpg`,
    galleryImages: [
        "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1000&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1000&auto=format&fit=crop"
    ],
    location: "Namur",
    medium: "Cuisine Artistique",
    subjects: ["Gastronomy", "Flavor", "Experience"],
    skills: ["Molecular Gastronomy", "Plating", "Fermentation", "Menu Design"],
    currentExpos: "Labo culinaire",
    stats: { creativity: 96, technique: 98, vision: 92 },
    bio: "Artiste culinaire redéfinissant les frontières du goût. Marc Alexis Pepin transforme chaque plat en une œuvre d'art éphémère, fusionnant techniques modernes et saveurs ancestrales dans son laboratoire culinaire.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 6,
    name: "Tania Martin",
    class: "Bardic Soul",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Tania.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique",
    subjects: ["Melody", "Rhythm"],
    skills: ["Vocals", "Guitar", "Songwriting"],
    stats: { creativity: 90, technique: 88, vision: 90 },
    bio: "Musicienne passionnée, Tania Martin tisse des mélodies qui résonnent avec l'âme. Son art traverse les genres pour créer une expérience auditive unique.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 7,
    name: "Sebastien Leblanc",
    class: "Violin Virtuoso",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Sebastien.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Violon",
    subjects: ["Classical", "Modern", "Strings"],
    skills: ["Violin", "Composition", "Teaching"],
    stats: { creativity: 92, technique: 97, vision: 89 },
    bio: "Maître du violon, Sebastien Leblanc fait chanter les cordes avec une précision émouvante. Ses performances sont une ode à la musique classique revisitée.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 8,
    name: "Louis-Julien Durso",
    class: "Stage Weaver",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}LouisJulien.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique : Auteur Compositeur Metteur en Scene",
    subjects: ["Composition", "Theater", "Performance"],
    skills: ["Stage Direction", "Composition", "Acting"],
    stats: { creativity: 98, technique: 92, vision: 95 },
    bio: "Artiste multidisciplinaire, Louis-Julien Durso ne se contente pas de jouer de la musique; il la met en scène. Auteur, compositeur et interprète, il crée des univers complets.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 9,
    name: "La Bronze",
    class: "Sonic Warrior",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}LaBronze.jpg`,
    galleryImages: [],
    location: "Montreal",
    medium: "Musique",
    subjects: ["Pop", "Rock", "Energy"],
    skills: ["Performance", "Drumming", "Vocals", "Acting"],
    stats: { creativity: 94, technique: 90, vision: 96 },
    bio: "Force de la nature sur scène, La Bronze allie poésie percutante et rythmes entraînants. Une énergie contagieuse qui ne laisse personne indifférent.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 10,
    name: "Leslie",
    class: "Mystery Siren",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Leslie.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique",
    subjects: ["Mysterion"],
    skills: ["Vocals", "Piano", "Atmosphere"],
    stats: { creativity: 89, technique: 87, vision: 90 },
    bio: "Une voix qui semble venir d'ailleurs. Leslie explore les facettes mystérieuses de la musique, invitant l'auditeur dans un voyage introspectif.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 11,
    name: "Captain Generous",
    class: "Groove Captain",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}CaptainGenerous.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique",
    subjects: ["Funk", "Soul", "Groove"],
    skills: ["Bass", "Rhythm", "Band Leading"],
    stats: { creativity: 93, technique: 91, vision: 94 },
    bio: "Le capitaine du groove. Captain Generous navigue sur les ondes sonores avec une générosité rythmique qui fait bouger les foules.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 12,
    name: "Magnetosphere",
    class: "Void Resonator",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Magnetosphere.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique Experimentale",
    subjects: ["Ambient", "Electronic", "Space"],
    skills: ["Synthesis", "Sound Design", "Performance"],
    stats: { creativity: 97, technique: 95, vision: 99 },
    bio: "Exploration sonore aux confins de la perception. Magnetosphere crée des paysages auditifs expérimentaux qui défient les conventions.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 13,
    name: "Charles - Antoine Goulet",
    class: "Word Smith",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}CharlesAntoine.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Poésie",
    subjects: ["Words", "Emotion", "Performance"],
    skills: ["Poetry", "Spoken Word", "Writing"],
    stats: { creativity: 92, technique: 90, vision: 94 },
    bio: "Poète de l'instant et de l'émotion brute. Charles-Antoine Goulet sculpte les mots pour en extraire l'essence de l'expérience humaine.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 14,
    name: "Max & Nora",
    class: "Street Mages",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}MaxNora.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Graffiti",
    subjects: ["Urban", "Color", "Street Art"],
    skills: ["Graffiti", "Murals", "Design"],
    stats: { creativity: 95, technique: 88, vision: 93 },
    bio: "Duo dynamique transformant les murs gris en toiles vibrantes. Max & Nora apportent la couleur et l'énergie du street art au cœur de la nature.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 15,
    name: "Cynthia Filion",
    class: "Muralist Chef",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}Cynthia.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Murales - Artiste peintre et chef de cuisine",
    subjects: ["Love", "Food", "Art"],
    skills: ["Murals", "Painting", "Cooking"],
    stats: { creativity: 96, technique: 92, vision: 95 },
    bio: "Fueled by love. Cynthia Filion est une force créatrice double : aussi habile avec un pinceau sur un mur qu'avec un couteau en cuisine.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 16,
    name: "Kyle Murray - Kmurrs",
    class: "Soundsmith",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Kyle.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique",
    subjects: ["Composition", "Rhythm"],
    skills: ["Composition", "Production", "Multi-instrumentalist"],
    stats: { creativity: 91, technique: 89, vision: 90 },
    bio: "Kyle Murray, alias Kmurrs, crée des univers sonores immersifs. Sa musique est un voyage constant entre tradition et modernité.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 17,
    name: "Charlotte l'Orage",
    class: "Lunar Scribe",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}Charlotte.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Écriture - Événements Lunaires",
    subjects: ["Moon", "Writing", "Mystic"],
    skills: ["Writing", "Event Hosting", "Rituals"],
    stats: { creativity: 94, technique: 90, vision: 96 },
    bio: "Gardienne des mots et des cycles lunaires. Charlotte l'Orage organise des événements célestes et écrit avec la puissance des éléments.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 18,
    name: "Claude Philippe Nolin",
    class: "Visual Sage",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}ClaudePhilippe.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Arts Visuels",
    subjects: ["Painting", "Abstraction"],
    skills: ["Painting", "Visual Arts", "History"],
    stats: { creativity: 93, technique: 95, vision: 92 },
    bio: "Un maître des arts visuels dont l'œuvre traverse le temps. Claude Philippe Nolin capture l'invisible pour le rendre visible.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 19,
    name: "Mariel Sharp",
    class: "Visionary Director",
    category: "DIGITAL",
    avatarUrl: `${ROSTER_BASE_URL}Mariel.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Cinema",
    subjects: ["Film", "Direction", "Storytelling"],
    skills: ["Directing", "Screenwriting", "Editing"],
    stats: { creativity: 97, technique: 94, vision: 98 },
    bio: "Cinéaste au regard perçant. Mariel Sharp réalise des œuvres cinématographiques qui défient les attentes et explorent la condition humaine.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 20,
    name: "Kamy Rheault",
    class: "Matter Shaper",
    category: "SCULPTURE",
    avatarUrl: `${ROSTER_BASE_URL}Kamy.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Art Actuel, Peinture, Sculpture, Installations",
    subjects: ["Installation", "Space", "Matter"],
    skills: ["Sculpture", "Installation", "Painting"],
    stats: { creativity: 96, technique: 93, vision: 97 },
    bio: "Artiste multidisciplinaire par excellence. Kamy Rheault façonne la matière et l'espace à travers la peinture, la sculpture et des installations immersives.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 21,
    name: "Alice Renard",
    class: "Story Weaver",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}AliceRenard.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Écriture",
    subjects: ["Fiction", "Prose", "Narrative"],
    skills: ["Creative Writing", "Storytelling", "Editing"],
    stats: { creativity: 93, technique: 96, vision: 91 },
    bio: "Une plume affûtée et une imagination débordante. Alice Renard tisse des histoires captivantes qui transportent le lecteur dans d'autres mondes.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 22,
    name: "Jean-Guilhem Barguès",
    class: "Digital Architect",
    category: "DIGITAL",
    avatarUrl: `${ROSTER_BASE_URL}JeanGuilhem.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Arts Numeriques",
    subjects: ["Cyberpunk", "Future", "Digital"],
    skills: ["Digital Art", "3D Design", "VR"],
    stats: { creativity: 98, technique: 99, vision: 95 },
    bio: "Architecte de réalités virtuelles. Jean-Guilhem Barguès crée des mondes numériques complexes et fascinants, repoussant les limites de l'art digital.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 23,
    name: "Zora Katsner",
    class: "Ink & Strings",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}Zora.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Tatouage, Huile, Violon, Decors",
    subjects: ["Tattoo", "Music", "Painting"],
    skills: ["Tattoo", "Violin", "Oil Painting", "Set Design"],
    stats: { creativity: 95, technique: 94, vision: 92 },
    bio: "Une artiste aux multiples talents. Zora Katsner manie l'aiguille de tatouage, le pinceau et l'archet de violon avec la même virtuosité.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 24,
    name: "Antony Lepage",
    class: "Audio Engineer",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}Antony.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Musique - Mixage Sonore",
    subjects: ["Mixing", "Sound", "Production"],
    skills: ["Audio Engineering", "Mixing", "Mastering"],
    stats: { creativity: 90, technique: 100, vision: 92 },
    bio: "L'oreille absolue du studio. Antony Lepage sculpte le son pour donner vie aux visions musicales des artistes, alliant technique et sensibilité.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 25,
    name: "Les Bobettes",
    class: "Polyphonic Sirens",
    category: "MUSIC",
    avatarUrl: `${ROSTER_BASE_URL}LesBobettes.jpg`,
    galleryImages: [],
    location: "Ripon",
    medium: "Musique: Chants Polyphoniques",
    subjects: ["Harmony", "Tradition", "Vocal"],
    skills: ["Polyphony", "Vocals", "Performance"],
    stats: { creativity: 92, technique: 95, vision: 90 },
    bio: "Un ensemble vocal envoûtant. Les Bobettes explorent les harmonies des chants polyphoniques, créant une texture sonore riche et traditionnelle.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 26,
    name: "Alice Traverse",
    class: "Dream Weaver",
    category: "VISUAL",
    avatarUrl: `${ROSTER_BASE_URL}AliceTraverse.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Art visuel-Médiums mixtes",
    subjects: ["Onirique", "Absurde", "Macabre"],
    skills: ["Mixed Media", "Illustration", "Surrealism"],
    stats: { creativity: 97, technique: 91, vision: 96 },
    bio: "Exploratrice de l'onirique et de l'absurde. Alice Traverse crée des œuvres figuratives qui mêlent le macabre au normal dans un style unique.",
    links: { buy: "#", website: "#", support: "#" }
  },
  {
    id: 27,
    name: "Alex Alisich",
    class: "Light Catcher",
    category: "DIGITAL",
    avatarUrl: `${ROSTER_BASE_URL}AlexAlisich.jpg`,
    galleryImages: [],
    location: "Petite Nation",
    medium: "Photographie",
    subjects: ["Light", "Moment", "Perspective"],
    skills: ["Photography", "Lighting", "Portrait"],
    stats: { creativity: 94, technique: 96, vision: 93 },
    bio: "Photographe de l'instant décisif. Alex Alisich capture la lumière et l'émotion, révélant la beauté cachée dans le quotidien.",
    links: { buy: "#", website: "#", support: "#" }
  }
];
