import { chromium } from 'playwright';
const OUT = '/private/tmp/claude-501/-Users-lesalondesinconnus/f14f9ec2-7c34-43f2-973b-ee55332ef317/scratchpad';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport:{width:1440,height:900} });
const page = await ctx.newPage();
await page.goto('https://inconnus-dome.web.app/', { waitUntil:'domcontentloaded', timeout:45000 });
await page.waitForTimeout(4500);
await page.screenshot({ path:`${OUT}/dome-back.png` });
console.log('ok');
await browser.close();
